name: HelloTribe
favicon: null
layout_spectrum: 0.18423315440304577
typography_spectrum: 0.9688011654652655
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.10659742495045066
  lightness: 0.5759476104285568
  saturation: 0.10869344533421099
  rhythmicContrast: 0.8743500630371273
purpose: []
